# Generated by Django 5.0.2 on 2024-03-26 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_movies_budget_remove_movies_director_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movies',
            name='release_date',
        ),
    ]
