# Generated by Django 5.0.2 on 2024-03-26 23:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_photo_memory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='memory',
            name='photos',
        ),
        migrations.AddField(
            model_name='photo',
            name='memory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='base.memory'),
            preserve_default=False,
        ),
    ]
