# Generated by Django 5.0.2 on 2024-03-28 23:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0008_chatroom_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='room',
        ),
        migrations.RemoveField(
            model_name='message',
            name='user',
        ),
        migrations.DeleteModel(
            name='ChatRoom',
        ),
        migrations.DeleteModel(
            name='Message',
        ),
    ]
